name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: 16
          - run: npm i
          - run: npm test
